name: Backport Issue Check

on:
  pull_request_target:
    branches:
      - v*-branch

permissions:
  contents: read

jobs:
  backport:
    name: Backport Issue Check
    runs-on: ubuntu-22.04
    if: github.repository == 'zephyrproject-rtos/zephyr'

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Check out source code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install Python dependencies
        run: |
          sudo pip3 install -U setuptools wheel pip
          pip3 install -U pygithub

      - name: Run backport issue checker
        env:
          GITHUB_TOKEN: ${{ secrets.ZB_GITHUB_TOKEN }}
        run: |
          ./scripts/release/list_backports.py \
            -o ${{ github.event.repository.owner.login }} \
            -r ${{ github.event.repository.name }} \
            -b ${{ github.event.pull_request.base.ref }} \
            -p ${{ github.event.pull_request.number }}
